name: gymca
channels:
  - conda-forge
dependencies:
# Dependencies
  - python=3.9
  - gym
  - numpy
  - matplotlib
  - scipy
  - seaborn
  - pyyaml
  - svgpath2mpl
# Development
  - black
  - isort
  - mypy
  - pytest
  - pytest-repeat
  - pytest-cov
  - pre-commit
  - ipdb
  - objprint
  - pytest-randomly
  - icecream
